### PR TITLE
Initial pass at a Code of Conduct

### PR DESCRIPTION
**Pull request by necaris**
Also added a more meaningful title to the default README. 

Open question: who are the "moderators", or people to contact, in the case of a conduct issue? Do we have a collective contact address?

### CODE REVIEW

**Comment by necaris** [comment]
@scooter-dangle @PureW :point_up:

**Review by purew — APPROVED** [review]
LGTM

**Comment by purew** [comment]
> Open question: who are the "moderators", or people to contact, in the case of a conduct issue? Do we have a collective contact address?

Is this in the context of zulip and/or zoom meetings?

**Comment by necaris** [comment]
> Is this in the context of zulip and/or zoom meetings?

I'd say both -- all "Rust DC" spaces should be governed by this, which means we need moderators for them all. At the moment this is Zulip, our meetups (whether over video or in person), and the GitHub org.

**Comment by scooter-dangle** [comment]
> Do we have a collective contact address?

I have the Rust.DC.Meetup `@` gmail.com email address. Currently it just forwards to my personal account. Maybe it would make sense to share access with other organizers?

> Open question: who are the "moderators", or people to contact, in the case of a conduct issue?

Maybe we can include a list in this repository?

**Comment by necaris** [comment]
+1 to both

**Pull request merged**
